# **Theoretical Questions:**





# 1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans: NumPy, short for Numerical Python, is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Here are some of its key purposes and advantages:

# Purpose of NumPy
1. Efficient Array Operations: NumPy enables the creation and manipulation of arrays that are more efficient than traditional Python lists, especially for large datasets.
2. Numerical Computation: It provides tools for performing mathematical and statistical operations on large datasets, making it essential for scientific computing and data analysis.
3. Support for Linear Algebra: NumPy includes functions for linear algebra, Fourier transforms, and random number generation, which are critical for many scientific applications.

# Advantages of NumPy
1. Performance: NumPy's arrays are implemented in C, which allows for faster operations compared to standard Python lists. This is especially significant for large data sets and computations.
2. Vectorization: NumPy supports vectorized operations, allowing users to perform element-wise operations without explicit loops. This leads to cleaner code and improves performance.
3. Multidimensional Arrays: Unlike standard Python lists, NumPy arrays can be multidimensional (e.g., 2D matrices, 3D tensors), which is essential for handling complex data structures in scientific applications.
4. Broadcasting: NumPy's broadcasting rules allow for operations on arrays of different shapes, making it easier to write flexible and efficient code.
5. Extensive Functionality: It comes with a rich set of built-in mathematical functions, enabling a wide range of computations from simple arithmetic to complex mathematical transformations.
6. Integration with Other Libraries: NumPy serves as the foundation for many other scientific libraries in Python, such as SciPy, pandas, and Matplotlib, enhancing its ecosystem for data analysis and visualization.

# Enhancing Python's Numerical Capabilities

NumPy significantly enhances Python's capabilities for numerical operations by providing:

Speed: Optimized performance for array operations compared to native Python lists.

Convenience: A more intuitive syntax for mathematical operations, reducing the complexity of code.

Functionality: Advanced features such as linear algebra routines and random number generation that are not available in standard Python.


# 2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Ans: In NumPy, both np.mean() and np.average() are used to calculate the average of an array, but they have some important differences in functionality and use cases.

np.mean()

Purpose: Computes the arithmetic mean of the array elements.

Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

Parameters:

a: Input array.

axis: Specifies the axis along which to compute the mean.

dtype: Optional; the type used in the computation.

out: Optional; an alternative output array.

keepdims: If True, the reduced axes are retained in the result.

Use Case: Use np.mean() when you want a straightforward arithmetic mean and do not need any additional weights for the data.

np.average()

Purpose: Computes the weighted average of the array elements.

Syntax: np.average(a, axis=None, weights=None, returned=False)

Parameters:

a: Input array.

axis: Specifies the axis along which to compute the average.

weights: Optional; an array of weights, must be the same shape as a.

returned: If True, the function returns a tuple with the average and the sum of weights.

Use Case: Use np.average() when you need to compute a weighted average, where different elements contribute differently to the final average based on their weights.

Comparison

Functionality:

np.mean() computes a simple average, treating all elements equally.

np.average() can accommodate weights, making it suitable for cases where some elements should contribute more than others.

Performance:

Both functions are generally efficient, but np.mean() is often faster because it does not handle weights.

# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D  arrays.

Ans: Reversing a NumPy array can be accomplished using slicing or the np.flip() function. Depending on whether you want to reverse along different axes, the approach will vary slightly for 1D and 2D arrays.

Reversing a 1D Array

For a 1D array, you can reverse it using slicing:

import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)

print("Reversed 1D array:", reversed_arr_1d)


# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types  in memory management and performance.

Ans: You can determine the data type of elements in a NumPy array using the .dtype attribute. This attribute provides the type of the elements contained in the array, which can be useful for understanding how the array will behave in terms of operations and memory usage.

Importance of Data Types

Memory Management:

Different data types consume different amounts of memory. For instance, an int32 uses 4 bytes, while an int64 uses 8 bytes. Choosing the appropriate data type can significantly affect the memory footprint of your application, especially when dealing with large datasets.

Using a smaller data type (like int8 or float32) when appropriate can reduce memory usage, which is crucial in environments with limited resources.

Performance:

Operations on arrays with smaller data types can be faster because they require less data to be processed. However, using a type that is too small might lead to overflow or underflow errors in calculations.

NumPy is optimized for performance, and certain operations can be much faster with specific data types. For example, operations on float32 arrays might be faster than on float64, but at the cost of precision.

Numerical Accuracy:

Choosing the right data type affects the precision of calculations. For instance, using float32 may lead to rounding errors in calculations that require high precision, whereas float64 provides more precision at the cost of memory.

Understanding the implications of data types is essential for scientific computing, where numerical accuracy is critical.

Compatibility with Libraries:

Different libraries may have different requirements for data types. For instance, certain machine learning libraries expect inputs in specific formats. Ensuring compatibility can help avoid runtime errors.

# 5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans: In NumPy, an ndarray (n-dimensional array) is the core data structure used for storing and manipulating numerical data. It provides a flexible and efficient way to handle large datasets, especially in scientific computing and data analysis.

Key Features of ndarrays

Homogeneous Data:

All elements in an ndarray must be of the same data type (e.g., all integers, all floats). This uniformity allows for efficient memory storage and computation.

Multidimensional:

ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), enabling the representation of scalars, vectors, matrices, and higher-dimensional tensors.

Contiguous Memory Allocation:

The data is stored in a contiguous block of memory, which enhances performance for numerical computations due to improved cache locality.

Vectorized Operations:

NumPy allows for vectorized operations, meaning you can perform operations on entire arrays without explicit loops. This leads to more concise code and improved performance.

Broadcasting:

NumPy supports broadcasting, which allows arithmetic operations between arrays of different shapes. This feature simplifies code and avoids the need for manually reshaping arrays.

Rich Functionality:

ndarrays come with a wide array of built-in functions for mathematical, statistical, and linear algebra operations, making them highly versatile for data analysis.

Indexing and Slicing:

Advanced indexing and slicing capabilities allow for easy manipulation of subsets of data, enabling complex data retrieval and modification.

Shape and Size:

The shape of an ndarray can be easily changed, and its dimensions can be queried using attributes like .shape and .ndim.

Differences from Standard Python Lists

Data Type Homogeneity:

NumPy: All elements must be of the same type, which optimizes memory usage and performance.

Python Lists: Can contain mixed data types (integers, strings, lists, etc.), leading to less efficient storage and processing.

Performance:

NumPy: Generally faster for numerical operations due to its implementation in C and optimized memory handling.

Python Lists: Slower for numerical computations, as operations typically require iteration through elements.

Memory Efficiency:

NumPy: More memory-efficient, as it allocates space for elements in a contiguous block.

Python Lists: Less memory-efficient due to the overhead associated with each element (a pointer to the object).

Functionality:

NumPy: Provides a comprehensive set of mathematical functions and capabilities tailored for numerical computing.

Python Lists: Have basic operations (append, pop, etc.) but lack specialized numerical functions.

Multidimensional Capability:

NumPy: Supports multi-dimensional arrays natively.

Python Lists: Can be nested to create multi-dimensional structures, but this is less efficient and more cumbersome to manage.

# 6.Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans: When dealing with large-scale numerical operations, NumPy arrays offer significant performance benefits over Python lists due to several factors related to memory management, computation efficiency, and vectorized operations. Below is an analysis of the key advantages of NumPy arrays in such contexts:

1. Memory Efficiency

Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory, unlike Python lists, which are arrays of pointers to objects scattered in memory. This contiguous layout allows NumPy to take advantage of lower-level optimizations such as better cache locality, which improves performance when accessing array elements.

Fixed-Type Elements: NumPy arrays hold elements of a single data type (e.g., all integers or all floats), whereas Python lists can hold heterogeneous types. This fixed-type structure enables more efficient memory usage and reduces the overhead required for type checking and handling.

Compact Representation: NumPy arrays use less memory per element because they don’t store additional metadata like Python lists do (e.g., dynamic resizing information or pointers for each element).

2. Vectorization and Element-wise Operations

Vectorized Operations: NumPy provides optimized C-level implementations for performing operations on entire arrays, such as element-wise addition, multiplication, or more complex mathematical functions. This is called vectorization. These operations are implemented in highly efficient, compiled code, reducing the need for Python's slower loops and providing a significant performance boost.

Parallel Execution: In some cases, NumPy can leverage multi-core processors to execute operations in parallel, taking advantage of modern CPUs and optimizing execution speed for large datasets. Many NumPy functions automatically utilize parallelism when appropriate.

3. Broadcasting

Efficient Broadcasting: NumPy arrays support broadcasting, which allows operations on arrays of different shapes without needing explicit replication of data. Broadcasting helps avoid the overhead of creating copies of arrays and allows operations to be applied efficiently to arrays of different sizes, matching dimensions in a way that is optimized for performance.

4. Optimized Computation

Vectorized Computations: Instead of explicitly iterating over elements, NumPy allows you to apply functions directly to entire arrays. For example, adding two large arrays element-wise in NumPy is a single operation under the hood, rather than the multiple steps involved in a Python list iteration. This reduces Python's interpretation overhead and can be orders of magnitude faster.

Use of Optimized Libraries: NumPy is built on top of highly optimized C and Fortran libraries (e.g., LAPACK, BLAS). These libraries provide optimized implementations for numerical tasks like matrix multiplication, linear algebra, and random number generation, significantly boosting the performance of those operations compared to equivalent Python list-based implementations.

5. Less Overhead in Computation

Avoiding Python Overhead: With NumPy, many operations can be carried out in compiled code, thus bypassing the overhead of the Python interpreter. Python lists, on the other hand, require explicit looping and interpretation in Python bytecode, which can be much slower for numerical operations.

6. Large-Scale Data Handling

In-memory Operations: NumPy's internal representation of arrays allows large datasets to be handled entirely in memory, using specialized data structures that are more efficient than Python's generic lists. As a result, when working with large numerical datasets (e.g., millions of elements), NumPy arrays can process and manipulate data much more efficiently than Python lists.

Memory Views and Slicing: NumPy allows "views" of arrays, which provide access to large slices of data without copying it into new arrays, saving both time and memory. This is crucial when working with large-scale data, as it avoids unnecessary memory duplication.

7. Parallelism and GPU Support (Optional)

Parallelism: While not inherently parallel, many NumPy operations can be parallelized at the implementation level, taking advantage of multi-core CPUs. For certain tasks, external libraries such as NumExpr or Dask can extend NumPy's parallel capabilities.

GPU Acceleration: NumPy is not GPU-accelerated by default, but other libraries like CuPy replicate the NumPy API while utilizing NVIDIA GPUs to significantly speed up numerical operations. This allows for even larger-scale operations to be performed with reduced computation time.

8. Rich Functionality and Integration

Comprehensive Mathematical Functions: NumPy provides a wide array of functions for linear algebra, statistics, Fourier transforms, random number generation, and other specialized operations that are optimized for numerical computations. These functions operate much faster than using equivalent Python code with lists or loops.

Seamless Integration: NumPy arrays integrate easily with other scientific libraries (like SciPy, Pandas, scikit-learn, etc.), allowing large-scale data manipulation and analysis. These libraries are built on NumPy, and often leverage its array structure to provide high-performance operations.

# 7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Ans: In NumPy, both vstack() and hstack() are functions that allow you to stack arrays together along different axes. These functions are used to combine multiple arrays into a single array, but they differ in how they stack the arrays:

vstack(): Stacks arrays vertically (along rows). This means it adds arrays along the first axis (axis 0).

hstack(): Stacks arrays horizontally (along columns). This means it adds arrays along the second axis (axis 1).

Let's break it down with examples to illustrate the differences between vstack() and hstack().

vstack() (Vertical Stack)

vstack() stacks arrays on top of each other. For this to work, the arrays must have the same number of columns (i.e., the same number of columns in each row, the same second dimension). The result is a larger array with more rows.

Example:

import numpy as np

# Create two 2D arrays (same number of columns)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack vertically using vstack
result_vstack = np.vstack((arr1, arr2))

print(result_vstack)

Output:

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

In this case, arr1 and arr2 are stacked on top of each other, resulting in a new array with 4 rows and 2 columns.

hstack() (Horizontal Stack)

hstack() stacks arrays side by side (horizontally). For this to work, the arrays must have the same number of rows (i.e., the same number of rows in each array, the same first dimension). The result is a larger array with more columns.

Example:

# Stack horizontally using hstack
result_hstack = np.hstack((arr1, arr2))

print(result_hstack)

Output:

[[1 2 5 6]
 [3 4 7 8]]

# 8.Explain the differences between fliplr() and flipud() methods in NumPy including their effects on various array dimensions.

Ans: In NumPy, both fliplr() and flipud() are methods used to flip the elements of an array along different axes, but they have different effects based on the axis of flipping:

fliplr(): Flips the array left to right (i.e., along the horizontal axis, or axis 1).

flipud(): Flips the array up to down (i.e., along the vertical axis, or axis 0).

**1.fliplr() – Flip Left to Right**

The fliplr() method flips an array horizontally, meaning it reverses the order of elements along each row (left-to-right). This operation only affects the columns (second axis, axis 1), so the rows themselves remain unchanged.

Example:

import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip left to right (fliplr)
flipped_arr = np.fliplr(arr)

print("Original array:")
print(arr)

print("\nFlipped left to right (fliplr):")
print(flipped_arr)

Output:

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped left to right (fliplr):
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Each row has been reversed, but the number of rows remains the same.

Effect on Shape: No change in the number of rows (shape along axis 0), but the elements in each row (axis 1) are reversed.

**2. flipud() – Flip Up to Down**

The flipud() method flips an array vertically, meaning it reverses the order of rows (top-to-bottom). This operation only affects the rows (first axis, axis 0), so the columns in each row remain unchanged.

Example:

# Flip up to down (flipud)
flipped_arr_ud = np.flipud(arr)

print("\nFlipped up to down (flipud):")
print(flipped_arr_ud)

Output:

Flipped up to down (flipud):
[[7 8 9]
 [4 5 6]
 [1 2 3]]

The rows have been reversed, but the number of columns remains unchanged.

Effect on Shape: No change in the number of columns (shape along axis 1), but the rows (axis 0) are reversed.

# 9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans: In NumPy, the array_split() method is used to split an array into multiple sub-arrays. This function is particularly useful when you need to divide a large array into smaller chunks or segments, for example, during data preprocessing or batch processing in machine learning tasks.

Syntax:

numpy.array_split(ary, indices_or_sections, axis=0)

Parameters:

ary: The input array to be split.

indices_or_sections:
  If an integer, it specifies the number of equal-sized sub-arrays to split the array into.
  If a sequence of integers, it specifies the indices at which to split the array. These indices must be within the bounds of the array.

axis: The axis along which to split the array. Default is 0 (split along rows). You can set this to 1 to split along columns (or any other axis for multidimensional arrays).

Return:

The function returns a list of sub-arrays. Each sub-array is a view (or a reference) of the original array.

Handling Uneven Splits:

If the array cannot be evenly split based on the specified number of sections or indices, array_split() will handle the uneven distribution by distributing the "extra" elements among the resulting sub-arrays. The array will be split as evenly as possible, but some sub-arrays may have one more element than others.

This is a key feature of array_split()—unlike some other splitting methods (e.g., split()), which require the array to be evenly divisible, array_split() automatically handles the uneven splitting gracefully by allowing some sub-arrays to have more elements.

# 10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Ans: In NumPy, vectorization and broadcasting are two key concepts that allow for efficient and optimized array operations, significantly speeding up computation compared to traditional approaches like using Python loops. These concepts allow NumPy to perform operations on arrays element-wise or across multiple dimensions, often using highly optimized, compiled C code, thus avoiding the slow overhead of Python’s interpretation.

Let’s explore both concepts in more detail and see how they contribute to the efficiency of NumPy.

1. Vectorization in NumPy

Concept:

Vectorization refers to the ability to apply operations directly to entire arrays or large chunks of data, rather than iterating through them element by element in Python loops. In other words, vectorization allows for element-wise operations to be applied to arrays without the need for explicit Python for loops.

NumPy achieves vectorization by using highly efficient C and Fortran libraries under the hood, such as BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra PACKage). These libraries are optimized for performance and can perform operations on entire arrays much faster than Python can iterate through them.

Benefits of Vectorization:

Performance: Vectorized operations are significantly faster than using explicit loops in Python because they are implemented in low-level compiled code (C and Fortran), which runs much faster than interpreted Python code.

Conciseness: Code using vectorized operations is more concise and readable because you can operate on entire arrays with simple expressions rather than writing complex loops.

Parallelism: Some vectorized operations are implicitly parallelized, leveraging multiple cores or SIMD (Single Instruction, Multiple Data) instructions, further speeding up computations.

Example of Vectorization:

Without vectorization, you would need to manually loop over elements in the array and apply the operation:

import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Without vectorization (using a loop)
result = np.zeros_like(a)
for i in range(len(a)):
    result[i] = a[i] + b[i]
print(result)

With vectorization, you can perform the same operation directly:

# With vectorization
result = a + b  # Element-wise addition
print(result)

Output:

[5 7 9]

The vectorized version is not only more concise but also faster, as NumPy performs the addition operation in compiled C code, which is much more efficient than looping in Python.

2. Broadcasting in NumPy

Concept:

Broadcasting is a powerful feature in NumPy that allows operations to be performed on arrays of different shapes and sizes. Broadcasting enables NumPy to perform element-wise operations on arrays that do not have the same dimensions or shape, by stretching (broadcasting) the smaller array across the larger array so that their shapes are compatible for element-wise operations.

Broadcasting follows a set of rules to determine how smaller arrays can be broadcast to match the shape of larger arrays. If the shapes are compatible, NumPy will automatically "expand" the smaller array along the necessary dimensions.

Rules of Broadcasting:

1.If the arrays have a different number of dimensions, the smaller-dimensional array is padded with ones on the left side until both arrays have the same number of dimensions.

2.The sizes of the dimensions must either be the same or one of the arrays must have a size of 1 in a given dimension. This allows NumPy to "stretch" the smaller array across the larger one.

Benefits of Broadcasting:

Memory Efficiency: Broadcasting eliminates the need to create copies of arrays to perform operations. Instead, NumPy "broadcasts" smaller arrays over the larger ones without allocating extra memory, thus improving memory efficiency.

Concise Code: Broadcasting allows you to perform operations between arrays of different shapes without needing to manually reshape or replicate data.

Performance: Broadcasting avoids the overhead of replicating arrays and can lead to more efficient, parallelizable operations.

Example of Broadcasting:

Suppose you want to add a scalar value to each element of an array:

import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Add a scalar value to each element
result = arr + 10
print(result)

Output:

[[11 12 13]
 [14 15 16]]

Here, the scalar 10 is broadcast across all the elements of the 2D array arr, without needing to manually replicate the scalar across the entire array.

Example of Broadcasting with Arrays of Different Shapes:
Suppose you want to add a 1D array to a 2D array:

# Create a 2D array and a 1D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

# Broadcast the 1D array over the 2D array
result = arr_2d + arr_1d
print(result)

Output:

[[11 22 33]
 [14 25 36]]

The 1D array [10, 20, 30] is broadcasted across each row of the 2D array arr_2d. Instead of manually reshaping or repeating the 1D array, NumPy broadcasts it across the corresponding dimensions of arr_2d.

# **Practical Questions:**

# 1.Create a 3x3 NumPy array with random integers between 1 and 100. Then,interchange its rows and columns.

Ans: To create a 3x3 NumPy array with random integers between 1 and 100, and then interchange its rows and columns (which is equivalent to taking the transpose of the array), we can follow these steps:

Step-by-Step:

Generate the 3x3 array with random integers.

Interchange rows and columns, which is done using the .T attribute (transpose) or the np.transpose() function in NumPy.

Here’s the code to do that:

import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Step 2: Interchange rows and columns (transpose the array)
transposed_arr = arr.T
print("\nTransposed Array (rows and columns interchanged):")
print(transposed_arr)


# 2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

Ans: To generate a 1D NumPy array with 10 elements and reshape it into different 2D arrays (2x5 and then 5x2), you can use the reshape() function in NumPy. The reshape operation does not modify the original array but returns a new array with the specified shape.

Steps:

Create a 1D array with 10 elements.

Reshape it into a 2x5 array.

Reshape it again into a 5x2 array.

Code:

import numpy as np

# Step 1: Create a 1D NumPy array with 10 elements
arr_1d = np.arange(10)  # Array with elements from 0 to 9

print("Original 1D Array:")

print(arr_1d)

# Step 2: Reshape it into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)

print("\nReshaped into a 2x5 array:")

print(arr_2x5)

# Step 3: Reshape it again into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)

print("\nReshaped into a 5x2 array:")

print(arr_5x2)


# 3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

Ans: To create a 4x4 NumPy array with random float values and then add a border of zeros around it to make a 6x6 array, we can use the np.pad() function. This function allows us to pad an array with values along its boundaries.

Steps:

Generate the 4x4 array with random float values.
Add a border of zeros around the array to create a 6x6 array.

Code:

import numpy as np

# Step 1: Create a 4x4 array with random float values
arr_4x4 = np.random.random((4, 4))  # Random floats between 0 and 1

print("Original 4x4 Array:")

print(arr_4x4)

# Step 2: Add a border of zeros to make it a 6x6 array
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with border of zeros:")

print(arr_6x6)


# 4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

Ans: To create an array of integers from 10 to 60 with a step of 5 using NumPy, you can use the np.arange() function, which generates an array with a specified start, stop, and step.

Code:

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5

arr = np.arange(10, 61, 5)

print(arr)


# 5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

Ans: You can apply various string transformations in NumPy using the np.char module, which provides vectorized string operations. These functions allow you to perform operations like converting to uppercase, lowercase, title case, and more on arrays of strings.

Here's how you can create a NumPy array of strings and apply different case transformations:

Code:

import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations using np.char functions

uppercase_arr = np.char.upper(arr)   # Convert to uppercase

lowercase_arr = np.char.lower(arr)   # Convert to lowercase

titlecase_arr = np.char.title(arr)   # Convert to title case

capitalize_arr = np.char.capitalize(arr)  # Capitalize first letter

# Print the results

print("Original Array:")

print(arr)

print("\nUppercase Array:")

print(uppercase_arr)

print("\nLowercase Array:")

print(lowercase_arr)

print("\nTitlecase Array:")

print(titlecase_arr)

print("\nCapitalized Array:")

print(capitalize_arr)


# 6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

Ans: To generate a NumPy array of words and insert a space between each character of every word, you can use the np.char module, which allows you to apply vectorized string operations. Specifically, you can use np.char.add() to insert spaces between characters in each word.

Here’s how to do that:

Code:

import numpy as np

# Create a NumPy array of words

arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word

spaced_arr = np.char.add(' ', np.char.join(' ', arr))

# Print the result

print("Original Array:")

print(arr)

print("\nArray with spaces between characters:")

print(spaced_arr)


# 7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

Ans: To perform element-wise operations (addition, subtraction, multiplication, and division) on two 2D NumPy arrays, you can directly use the arithmetic operators (+, -, *, /). NumPy will automatically handle element-wise operations between arrays of the same shape.

Example Code:

import numpy as np

# Create two 2D NumPy arrays

arr1 = np.array([[1, 2, 3], [4, 5, 6]])

arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Element-wise addition

add_result = arr1 + arr2

# Element-wise subtraction

sub_result = arr1 - arr2

# Element-wise multiplication

mul_result = arr1 * arr2

# Element-wise division

div_result = arr1 / arr2

# Print the results

print("Array 1:")

print(arr1)

print("\nArray 2:")

print(arr2)

print("\nElement-wise Addition:")

print(add_result)

print("\nElement-wise Subtraction:")

print(sub_result)

print("\nElement-wise Multiplication:")

print(mul_result)

print("\nElement-wise Division:")

print(div_result)


# 8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

Ans: In NumPy, you can create a 5x5 identity matrix using the np.eye() function, which generates an identity matrix (a square matrix with ones on the diagonal and zeros elsewhere). After that, you can extract the diagonal elements using the np.diagonal() method.

Code:

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

# Print the results
print("5x5 Identity Matrix:")

print(identity_matrix)

print("\nDiagonal Elements:")

print(diagonal_elements)


# 9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

Ans: To generate an array of 100 random integers between 0 and 1000, and then find and display all the prime numbers in this array, you can follow these steps:

Generate the array of random integers using np.random.randint().

Define a function to check if a number is prime.

Filter the prime numbers from the array using the prime checking function.

Code:

import numpy as np

# Function to check if a number is prime

def is_prime(num):

    if num <= 1:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a 1D array of 100 random integers between 0 and 1000

arr = np.random.randint(0, 1001, size=100)

# Filter the prime numbers from the array

prime_numbers = [num for num in arr if is_prime(num)]

# Print the results

print("Generated Array:")

print(arr)

print("\nPrime Numbers in the Array:")

print(prime_numbers)


# 10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

Ans: To create a NumPy array representing daily temperatures for a month (30 days, for example), and then calculate the weekly averages, we can follow these steps:

Generate the daily temperatures: This can be done by creating a NumPy array of random values representing temperatures.

Reshape the array: The 30-day array can be reshaped into a 2D array where each row represents a week (i.e., 4 rows for 4 weeks).

Calculate weekly averages: We can calculate the average of each row (representing a week) using the np.mean() function along the correct axis.

Code:

import numpy as np

# Step 1: Generate a NumPy array of daily temperatures for a month (30 days)

# Assuming temperatures are between 15 and 35 degrees Celsius

daily_temperatures = np.random.randint(15, 36, size=30)

# Step 2: Reshape the array into a 2D array with 4 weeks (4 rows) and 7 days each (7 columns)

weekly_temperatures = daily_temperatures.reshape(4, 7)

# Step 3: Calculate the weekly averages

weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the results

print("Daily Temperatures for the Month:")

print(daily_temperatures)

print("\nWeekly Temperatures (4 weeks, 7 days each):")

print(weekly_temperatures)

print("\nWeekly Averages:")

print(weekly_averages)
